[2022-12-15T06:08:22.979+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: twitter_etl.extract scheduled__2022-12-15T00:07:10.585416+00:00 [queued]>
[2022-12-15T06:08:22.989+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: twitter_etl.extract scheduled__2022-12-15T00:07:10.585416+00:00 [queued]>
[2022-12-15T06:08:22.989+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2022-12-15T06:08:22.989+0000] {taskinstance.py:1363} INFO - Starting attempt 2 of 2
[2022-12-15T06:08:22.989+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2022-12-15T06:08:23.005+0000] {taskinstance.py:1383} INFO - Executing <Task(BashOperator): extract> on 2022-12-15 00:07:10.585416+00:00
[2022-12-15T06:08:23.009+0000] {standard_task_runner.py:55} INFO - Started process 211 to run task
[2022-12-15T06:08:23.011+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'twitter_etl', 'extract', 'scheduled__2022-12-15T00:07:10.585416+00:00', '--job-id', '10', '--raw', '--subdir', 'DAGS_FOLDER/dags.py', '--cfg-path', '/tmp/tmp37h8h3yw']
[2022-12-15T06:08:23.012+0000] {standard_task_runner.py:83} INFO - Job 10: Subtask extract
[2022-12-15T06:08:23.067+0000] {task_command.py:376} INFO - Running <TaskInstance: twitter_etl.extract scheduled__2022-12-15T00:07:10.585416+00:00 [running]> on host 894f95b970dd
[2022-12-15T06:08:23.124+0000] {taskinstance.py:1590} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=lambobr1994@gmail.com
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=twitter_etl
AIRFLOW_CTX_TASK_ID=extract
AIRFLOW_CTX_EXECUTION_DATE=2022-12-15T00:07:10.585416+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-12-15T00:07:10.585416+00:00
[2022-12-15T06:08:23.125+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2022-12-15T06:08:23.125+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'python3 /opt/***/python_scripts/start_dms.py']
[2022-12-15T06:08:23.133+0000] {subprocess.py:86} INFO - Output:
[2022-12-15T06:08:23.694+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2022-12-15T06:08:23.694+0000] {subprocess.py:93} INFO -   File "/opt/***/python_scripts/start_dms.py", line 7, in <module>
[2022-12-15T06:08:23.694+0000] {subprocess.py:93} INFO -     with open(r'C:\Users\lambo\PycharmProjects\pythonProject\ETL_projects\aws-offsec\dms_config.json') as file:
[2022-12-15T06:08:23.695+0000] {subprocess.py:93} INFO - FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\lambo\\PycharmProjects\\pythonProject\\ETL_projects\\aws-offsec\\dms_config.json'
[2022-12-15T06:08:23.729+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2022-12-15T06:08:23.737+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/bash.py", line 196, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2022-12-15T06:08:23.740+0000] {taskinstance.py:1401} INFO - Marking task as FAILED. dag_id=twitter_etl, task_id=extract, execution_date=20221215T000710, start_date=20221215T060822, end_date=20221215T060823
[2022-12-15T06:08:23.752+0000] {standard_task_runner.py:100} ERROR - Failed to execute job 10 for task extract (Bash command failed. The command returned a non-zero exit code 1.; 211)
[2022-12-15T06:08:23.786+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2022-12-15T06:08:23.804+0000] {taskinstance.py:2623} INFO - 0 downstream tasks scheduled from follow-on schedule check
